// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	GetDetails(ctx context.Context, opts ...grpc.CallOption) (BookService_GetDetailsClient, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) GetDetails(ctx context.Context, opts ...grpc.CallOption) (BookService_GetDetailsClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[0], "/book.BookService/GetDetails", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceGetDetailsClient{stream}
	return x, nil
}

type BookService_GetDetailsClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type bookServiceGetDetailsClient struct {
	grpc.ClientStream
}

func (x *bookServiceGetDetailsClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bookServiceGetDetailsClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	GetDetails(BookService_GetDetailsServer) error
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) GetDetails(BookService_GetDetailsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDetails not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_GetDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BookServiceServer).GetDetails(&bookServiceGetDetailsServer{stream})
}

type BookService_GetDetailsServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type bookServiceGetDetailsServer struct {
	grpc.ServerStream
}

func (x *bookServiceGetDetailsServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bookServiceGetDetailsServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "book.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDetails",
			Handler:       _BookService_GetDetails_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "book_service.proto",
}
