// Code generated by MockGen. DO NOT EDIT.
// Source: grpc-bidirectional-bookdetails/grpc (interfaces: BookService_GetDetailsServer)

// Package mock_grpc is a generated GoMock package.
package mock_grpc

import (
	context "context"
	grpc "grpc-bidirectional-bookdetails/grpc"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockBookService_GetDetailsServer is a mock of BookService_GetDetailsServer interface.
type MockBookService_GetDetailsServer struct {
	ctrl     *gomock.Controller
	recorder *MockBookService_GetDetailsServerMockRecorder
}

// MockBookService_GetDetailsServerMockRecorder is the mock recorder for MockBookService_GetDetailsServer.
type MockBookService_GetDetailsServerMockRecorder struct {
	mock *MockBookService_GetDetailsServer
}

// NewMockBookService_GetDetailsServer creates a new mock instance.
func NewMockBookService_GetDetailsServer(ctrl *gomock.Controller) *MockBookService_GetDetailsServer {
	mock := &MockBookService_GetDetailsServer{ctrl: ctrl}
	mock.recorder = &MockBookService_GetDetailsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookService_GetDetailsServer) EXPECT() *MockBookService_GetDetailsServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockBookService_GetDetailsServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockBookService_GetDetailsServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockBookService_GetDetailsServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockBookService_GetDetailsServer) Recv() (*grpc.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*grpc.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockBookService_GetDetailsServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockBookService_GetDetailsServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockBookService_GetDetailsServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockBookService_GetDetailsServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockBookService_GetDetailsServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockBookService_GetDetailsServer) Send(arg0 *grpc.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBookService_GetDetailsServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBookService_GetDetailsServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockBookService_GetDetailsServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockBookService_GetDetailsServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockBookService_GetDetailsServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockBookService_GetDetailsServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockBookService_GetDetailsServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockBookService_GetDetailsServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockBookService_GetDetailsServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockBookService_GetDetailsServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockBookService_GetDetailsServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockBookService_GetDetailsServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockBookService_GetDetailsServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockBookService_GetDetailsServer)(nil).SetTrailer), arg0)
}
